public class SalesforceDevoleper {
    public void myFirstCode(){
        string favCity = 'Paris';
        string favMovie = 'Brave Heart';
        string favSeason = 'Spring';

        system.debug(favCity);
        system.debug(favMovie);
        system.debug(favSeason);

    }

    public void myFavorites(){
        string favCity2 = 'Paris';
        integer favNum = 7;

        system.debug(favCity2);
        system.debug(favNum);
    }

}
