Cat sfCat = new Cat();
sfCat.name = 'ginger';
sfCat.color = 'orange';
system.debug('sfCat '+ sfCat);

system.debug('number of cats ' + cat.countCat);

Cat FalconCat = new Cat('fluffykins', 'white');
system.debug('falconCat ' + falconCat);

Cat batch12Cat = new Cat('simba', 'white');
system.debug('falconCat ' + batch12Cat);

Cat batch12Cat3 = new Cat('blackpaper', 'black');
system.debug('falconCat ' + batch12Cat);

system.debug('number of cats ' + cat.countCat);